const fs = require('fs');
const si = require('react-icons/si');
console.log("SiHtml5:", !!si.SiHtml5);
console.log("SiCss3:", !!si.SiCss3);
console.log("SiJavascript:", !!si.SiJavascript);
console.log("SiReact:", !!si.SiReact);
console.log("SiNodedotjs:", !!si.SiNodedotjs);
console.log("SiMongodb:", !!si.SiMongodb);
console.log("SiMysql:", !!si.SiMysql);
console.log("SiPostgresql:", !!si.SiPostgresql);
console.log("SiGooglecloud:", !!si.SiGooglecloud);
console.log("SiGit:", !!si.SiGit);
console.log("SiSwagger:", !!si.SiSwagger);
console.log("SiDocker:", !!si.SiDocker);
console.log("SiExpress:", !!si.SiExpress);
console.log("SiRedux:", !!si.SiRedux);
console.log("SiGooglebigquery:", !!si.SiGooglebigquery);
console.log("SiRedis:", !!si.SiRedis);
console.log("SiRabbitmq:", !!si.SiRabbitmq);
console.log("SiSocketdotio:", !!si.SiSocketdotio);
console.log("SiSequelize:", !!si.SiSequelize);
console.log("SiTypeorm:", !!si.SiTypeorm);
console.log("SiPwa:", !!si.SiPwa);
